global:
  scrape_interval: "5s"

scrape_configs:
- job_name: psudaemon
  metrics_path: /probe
  params:
    module: [default]
  static_configs:
    - targets:
      - "http://localhost:5000/monitoring/channels"
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - source_labels: [__address__]
      target_label: __address__
      regex: '^https?://([^:]*):(.*)/*'
      replacement: "${1}:7979"
