version: '3'

services:
  psudaemon:
    container_name: psudaemon
    image: psudaemon:latest
    build: ../
    network_mode: host
    ports:
      - 5000:5000
    volumes:
      - ../conf/psudaemon.yaml:/config.yaml
    environment:
      - PSUDAEMON_CONF=/config.yaml
