{
 "title": "psudaemon",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "psu", "label": "PSU", "query": { "query": "label_values(psu)" } },
   {
    "name": "ch",
    "label": "CH",
    "query": {
     "query": "label_values({psu=\"$psu\"},index)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values({psu=\"$psu\", index=\"$ch\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$psu CH$ch: $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ch" },
  {
   "title": "$psu:$ch state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "channel_data_state{psu=\"$psu\", index=\"$ch\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$psu:$ch Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "channel_data_state{psu=\"$psu\", index=\"$ch\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$psu:$ch Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "channel_data_voltage{psu=\"$psu\", index=\"$ch\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$psu:$ch Current Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "channel_data_current_limit{psu=\"$psu\", index=\"$ch\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$psu:$ch Time ON",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$last_on - $last_off", "type": "math" }
   ]
  },
  {
   "title": "$psu:$ch Voltage limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "channel_data_voltage_limit{psu=\"$psu\", index=\"$ch\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$psu:$ch Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "channel_data_current{psu=\"$psu\", index=\"$ch\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Current and Voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CH$ch ($name) Voltage and Current",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "channel_data_current{index=~\"$ch\", psu=\"$psu\"}",
     "legendFormat": "{{name}} Current"
    },
    {
     "expr": "channel_data_current_limit{psu=\"$psu\", index=~\"$ch\"}",
     "legendFormat": "{{name}} Current Limit"
    },
    {
     "expr": "channel_data_voltage{index=~\"$ch\", psu=\"$psu\"}",
     "legendFormat": "{{name}} Voltage"
    }
   ]
  }
 ]
}